---
# have to import and enable GPG keys before install repo file. with dnf this seems to be done automagically but not with ansible module

- name: 
  hosts: localhost
  connection: local
  become: True
  gather_facts: True
  tasks:

    # - name: debug ansible distro version
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_distribution_version }}"

    # - name: install distribution RPM GPG keys
    #   ansible.builtin.dnf:
    #     name: distribution-gpg-keys
    #     state: present

    - name: enable GPG keys
      ansible.builtin.rpm_key:
        key: "{{ item }}"
        state: present
      with_items:
        - "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_version }}"
        - "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_version }}"

    - name: install RPM Fusion free and nonfree repos
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
...